/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "YOU ARE AT A WALL.": "你在墙边。",
    "Scroll down!": "向下滚动！",
    "Energy Upgrades:": "能量升级：",
    "Exit challenge": "退出挑战",
    "An incremental that will reach ExpantaNum's limit.": "将达到 扩展数字 限制的增量。",
    "AND": "精神",
    "autobuyers": "汽车买家",
    "Automation": "自动化",
    "B - Buy a Booster": "B - 购买助推器",
    "Booster Rebuyables Autobuyer (Disabled)": "助推器可重购自动购买者（已禁用）",
    "Booster Rebuyables Autobuyer (Enabled)": "助推器可重购自动购买者（已启用）",
    "Boosters": "助推器",
    "Boosters Autobuyer (Disabled)": "助推器 Autobuyer（已禁用）",
    "Boosters Autobuyer (Enabled)": "助推器自动购买（已启用）",
    "BUY BOOSTER": "购买助推器",
    "CHALLENGES": "挑战",
    "CHANGELOG": "更新日志",
    "Click a subtab!": "单击子选项卡！",
    "Click this button to finish your journey!": "点击此按钮完成您的旅程！",
    "Completing all challenges unlocks": "完成所有挑战解锁",
    "Contributors:": "贡献者：",
    "You have explored": "你已经探索过了",
    "YOU HAVE EXPLORED THE PLANET!": "你已经探索了这个星球！",
    "You need at least 1e7 points.": "您至少需要 1e7 点数。",
    "Ultimate Incremental": "终极增量",
    "A - Toggle Automators": "A - 切换自动化装置",
    "A challenge resets everything pre-space, so be sure to get all the power and space rebuyables you can get before starting a challenge.": "挑战会重置空间前的所有内容，因此请确保在开始挑战之前获得所有可以获得的能量和空间可重复购买。",
    "Air": "空气",
    "Cost: {{format(rebuyableCost(\"space\",0,true))}} space": "成本: {{format(rebuyableCost(\"space\",0,true))}} 空间",
    "Exit challenges on this layer. This will also complete any challenges you have the requirements for.": "退出这一层的挑战。 这也将完成您有要求的任何挑战。",
    "Exit your current challenge.": "退出当前的挑战。",
    "Explode planet!": "炸毁这个星球！",
    "Explore the planet more for another wall.": "更多地探索这个星球，寻找另一面墙。",
    "F - Perform a Fly Reset": "F - 执行飞行重置",
    "Cost: {{rebuyableCost(\"boosters\",0)}} boosters.": "成本: {{rebuyableCost(\"boosters\",0)}} 助推器.",
    "Cost: {{rebuyableCost(\"energy\",0,false)}} energy.": "成本: {{rebuyableCost(\"energy\",0,false)}} 能量.",
    "E - Buy Energy": "E - 购买能量",
    "ENERGY": "能量",
    "Energy": "能量",
    "FLY": "飞行",
    "Fly": "飞行",
    "GAIN POWER": "获得能量",
    "Hard Reset": "硬重置",
    "Get all this to break through the wall.": "得到这一切来打破墙。",
    "Join the discord server!": "加入 discord 服务器!",
    "Main": "主界面",
    "Lose {{format(flyData.gain())}} boosters": "失去 {{format(flyData.gain())}} 助推器",
    "P - Toggle Power Gain": "P - 切换能量增益",
    "PLAY": "开始",
    "Planets": "星球",
    "Power": "能量",
    "Space": "空间",
    "You can not fly right now.": "你现在不能飞。",
    "You don't have enough power, get {{format(energyData.cost())}} and try again.": "你没有足够的能量，得到 {{format(energyData.cost())}} 然后再试一次。",
    "You enter and finish a challenge by clicking on the challenge.": "您可以通过单击挑战进入并完成挑战。",
    "You have currently collected {{ getTotalAchsCompleted() }}/{{ Object.keys(achievementData).length }} achievements.": "你当前收集了 {{ getTotalAchsCompleted() }}/{{ Object.keys(achievementData).length }} 成就.",
    "You need the following to break through the wall:": "您需要以下内容才能突破围墙：",
    "Back To Basics!": "回归本源！",
    "Boosting To The Max!": "提升到最大！",
    "Buy a Booster.": "购买助推器。",
    "Buy booster": "购买助推器",
    "Complete All Of The Energy Challenges.": "完成所有能源挑战。",
    "Complete the current Endgame.": "完成当前的残局。",
    "Courier": "导游",
    "Cubedey- Style creation and some achievement work": "Cubedey-风格创作和一些成就作品",
    "Dark": "黑暗的",
    "Decrease base booster costs by 20%.": "将基础助推器成本降低 20%。",
    "Double point gain.": "双倍积分。",
    "Electric Boogaloo": "电动布加洛",
    "Energetic!": "精力充沛！",
    "Gapples": "间隙",
    "I Believe I Can Fly!": "我相信我能飞！",
    "I Need More Space!": "我需要更多空间！",
    "I’m a Watt?": "我是瓦特？",
    "Ima Need Some Eye Bleach...": "我需要一些眼部漂白剂...",
    "Insert Rhyme Here.": "在此处插入押韵。",
    "Light": "光",
    "Lose a Booster.": "失去一个助推器。",
    "Lucida Console": "露西达控制台",
    "MEME - Making some of the upgrades and buyables": "MEME - 进行一些升级和购买",
    "Not So Challenging...": "不那么具有挑战性...",
    "NOTE: The patch that is not white is the most recent.": "注意：不是白色的补丁是最新的。",
    "You are currently gaining power.": "你目前正在获得能量。",
    "You are currently not gaining power.": "你目前没有获得权力。",
    "unpingabot - saving and loading": "unpingabot - 保存和加载",
    "Upon flying, you will:": "飞行后，您将：",
    "Use this if you get stuck.": "如果您遇到困难，请使用它。",
    "THERE ARE NO VISIBLE WALLS YET.": "还没有可见的墙壁。",
    "This is boosting your points by {{format(powerData.boost())}}x.": "这提高了您的点数 {{format(powerData.boost())}}x。",
    "This will also complete any challenges you have the requirements for.": "这也将完成您有要求的任何挑战。",
    "This will remove the current planet you are on.": "这将删除您当前所在的星球。",
    "Toggle autobuyers by clicking on their buttons or by pressing a.": "通过单击按钮或按 a 来切换自动购买者。",
    "Try getting 4 boosters....": "尝试获得4个助推器....",
    "Try getting 7 boosters. That might help....": "尝试获得 7 个助推器。 这可能会有所帮助....",
    "UNLIMITED POWER!": "无限的能量！",
    "Unlock Energy.": "解锁能量。",
    "Unlock Power.": "解锁电源。",
    "Unlock Space.": "解锁空间。",
    "of the planet.": "星球。",
    "Options": "选项",
    "Out Of This World!": "离开这个世界！",
    "Reward: Unlock Stars.": "奖励：解锁星星。",
    "Select The Tree Style.": "选择树样式。",
    "Semenar - various fixes": "Semenar - 各种修复",
    "Shift + P - Buy a Planet/Bypass a Wall": "Shift + P - 购买星球/绕过墙壁",
    "Solar System": "太阳系",
    "Space Rebuyables Autobuyer (Disabled)": "空间可重购自动购买（已禁用）",
    "Space Rebuyables Autobuyer (Enabled)": "空间可重购自动购买（已启用）",
    "Street Dance Crew": "街舞团",
    "TheMKeyHolder - making code better, achs system, and offline progress": "TheMKeyHolder - 使代码更好，achs 系统和离线进度",
    "Find a planet for {{format(planetData.cost())}} points!": "寻找一个星球花费 {{format(planetData.cost())}} 点数!",
    "obtain {{format(airData.gain())}} air": "获取 {{format(airData.gain())}} 空气",
    "There are {{format(Object.keys(player.planets.planet[player.planets.amt.toNumber()].walls).length)}} walls on this planet.": "这个星球上有 {{format(Object.keys(player.planets.planet[player.planets.amt.toNumber()].walls).length)}} 墙.",
    "When you gain power, your points get divided by {{powerData.lossEffectOnPoints().toFixed(2)}} every second, AND you don't gain any points.": "当你获得能量时, 你的点数每秒除以 {{powerData.lossEffectOnPoints().toFixed(2)}} , 并且你将不会获得任何点数.",
    "You are losing {{format(player.points.div(hasUpgrade(\"energy\",0)?4:2))}} points every second.": "你每秒失去 {{format(player.points.div(hasUpgrade(\"energy\",0)?4:2))}} 点数.",
    "You have completed all of the current achievements. Congratulations!": "您已完成所有当前成就。 恭喜！",
    "Halve energy requirements.": "将能量需求减半。",
    "Obtain a free booster.": "获得一个免费的助推器。",
    "Reward: Air's effect on points is x^1.15.": "奖励：空气对点数的影响是 x^1.15。",
    "Reward: Boosters’ cost scaling is 0.9x stronger (after EC1's effect).": "奖励：助推器的成本比例是 0.9x（在 EC1 的影响之后）。",
    "Reward: Boosters’ cost scaling is 0.9x stronger, and point gain is multiplied by 1.5x.": "奖励：助推器的成本比例是 0.9x，点数增益乘以 1.5x。",
    "Double power's base effect.": "双倍能量的基础效果。",
    "While you're in this challenge ANYTHING air-related does nothing. EC1's nerf is applied.": "当你在这个挑战中时，任何与空气有关的东西都不起作用。 应用了 EC1 的 nerf。",
    "While you're in this challenge Base booster cost scaling is set to 4.2069x instead of 3.00x. EC3's nerfs are applied.": "当你面临这个挑战时，基础助推器成本缩放设置为 4.2069 倍而不是 3.00 倍。 应用了 EC3 的 nerfs。",
    "While you're in this challenge EVERY multiplier to point gain is square-rooted. However, your point gain is multiplied by 3, and then raised to ^1.5.": "当你在这个挑战中时，每一个点增益的乘数都是平方根的。 但是，您的积分增益乘以 3，然后提高到 ^1.5。",
    "While you're in this challenge Point gain is raised to the amount of stniop you have. Stniop decreases by 0.01 (starting at 1.00) every second, stopping at 0.01. EC2's nerfs are applied.": "当您处于此挑战中时，积分增益将提高到您拥有的 stniop 数量。 Stniop 每秒减少 0.01（从 1.00 开始），在 0.01 处停止。 应用了 EC2 的 nerfs。",
    "Reward: Point production is x^1.05.": "奖励：点数为 x^1.05。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Emi - Some Achievement Work": "Emi - 一些成就工作",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'Cancer': 'Cancer',
    'Arial': 'Arial',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Rebuyable ": "可重购 ",
    "Booster Rebuyable ": "助推器可重购 ",
    "Amount Bought: ": "已购买数量：",
    "Cost Scaling: ": "成本比例：",
    "Effect: ": "效果：",
    "Energy Rebuyable ": "能量可重购 ",
    "Style: ": "样式：",
    "Amount: ": "数量: ",
    "Boost point gain based on air AND multiply point gain by ": "基于空气的提升点数增益并将点数增益乘以 ",
    "Font: ": "字体：",
    "Current End-game: ": "当前游戏终点：",
    "You are on planet ": "你所在的星球是 ",
    "Energy Challenge ": "能量挑战 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^成本比例(.+)$/,
    /^你有(.+)$/,
    /^这提高了您的(.+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You are gaining (.+) points every second.$/, '您每秒获得 $1 点数。'],
    [/^You have (.+) power \((.+)\/s\).$/, '你有 $1 能量（$2\/秒）。'],
    [/^You have (.+) energy, which boosts power gain by (.+).$/, '你有 $1 能源，这会使能量增益提高 $2。'],
    [/^Obtain (.+) Planet.$/, '获得 $1 个星球。'],
    [/^Obtain (.+) Planets.$/, '获得 $1 个星球。'],
    [/^Obtain (.+) Energy.$/, '获得 $1 能源。'],
    [/^You have (.+) air.$/, '你有 $1 空气。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) points.$/, '你有 $1 点数.'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) air$/, '成本：$1 空气'],
    [/^Cost: (.+) space$/, '成本：$1 空间'],
    [/^Cost: (.+) boosters.$/, '成本：$1 助推器。'],
    [/^Cost: (.+) energy.$/, '成本：$1 能量。'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Goal: (.+) space$/, '目标：$1 空间'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);